Add docker archive scan
GitGuardian/gg-shield pull request #71
Opened 2021-06-14 13:28 UTC by Jguer

- Add `ggshield scan docker` command

2021-06-14 15:02 UTC, julienc91 requested changes

2021-06-14 15:07 UTC, Walz reviewed
I've tested the code on ~300 images and except the issue with `.decode(errors="replace").replace("\0", "�")`, everything looks good to me.

2021-06-14 15:53 UTC, Jguer commented on ggshield/scan/docker.py
> +        file_content = file_content_raw.decode(errors="replace").replace("\0", "�")
:sweat_smile:  not sure why actually, didn't write this part but I'll be changing it

2021-06-14 15:55 UTC, Jguer commented on ggshield/scan/docker.py
> +        if len(file_content_raw) > MAX_FILE_SIZE * 0.95:
really going to the tightest of limits results in weird edge cases, i'd leave this as a safety margin

2021-06-15 12:43 UTC, Jguer commented on ggshield/scan/docker.py
> +    return "COPY" in cmd or "ADD" in cmd
it was perfect, it just missed r"\b(copy|add)\b" to work

2021-06-15 13:05 UTC, julienc91 commented on README.md
> +    ggshield will try to pull the image if it's not available localy
`locally`

2021-06-15 13:15 UTC, julienc91 approved these changes

2021-06-15 13:35 UTC, Walz approved these changes

2021-06-15 13:39 UTC, merged